# Generated by Django 5.2 on 2025-04-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_employee_hire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_department_head",
            field=models.BooleanField(default=False),
        ),
    ]
